CREATE TABLE USER_AUTHEN (
  USER_ID NUMBER PRIMARY KEY
 ,USERNAME VARCHAR(50)
 --,DISPLAY_NAME NVARCHAR(100)
 ,HASH_PASS VARCHAR(50)
 ,HASS_SALT VARCHAR(50)
 ,STATUS NUMBER
 ,LOGIN_TYPE NUMBER
 ,DATE_CREATED DATE
);

CREATE TABLE CONVERSATION (
 CONVERSATION_ID NUMBER PRIMARY KEY
 ,SUBJECT NVARCHAR2(200)
 ,DATE_CREATED DATE
);

CREATE TABLE USER_CONV (
  CONVERSATION_ID NUMBER
 ,USER_ID NUMBER
 ,STATUS NUMBER
 ,DATE_CREATED DATE
);

CREATE TABLE MESSAGE (
  MESSAGE_ID NUMBER PRIMARY KEY
 ,MESS_BODY NVARCHAR2(500)
 ,STATUS NUMBER
 ,MESS_TYPE NUMBER
 ,FROM_USER_ID NUMBER
 ,CONVERSATION_ID NUMBER
 ,DATE_SENT DATE
 ,DATE_DELIVERED DATE
);

CREATE TABLE BUDDY (
  USER_ID NUMBER
 ,BUDY_ID NUMBER
 ,STATUS NUMBER
 ,DATE_CREATED DATE
);
