CREATE TABLE USER_AUTHEN (
  USER_ID NUMBER PRIMARY KEY
 ,USERNAME VARCHAR(50)
 --,DISPLAY_NAME NVARCHAR(100)
 ,HASH_PASS VARCHAR(50)
 ,HASH_SALT VARCHAR(50)
 ,STATUS NUMBER
 ,LOGIN_TYPE NUMBER
 ,DATE_CREATED DATE
);
COMMENT ON COLUMN USER_AUTHEN.LOGIN_TYPE IS '0: Local; 1: LDAP';

CREATE SEQUENCE SEQ_USER_ID;
CREATE UNIQUE INDEX IDX_USERNAME ON USER_AUTHEN (USERNAME);

CREATE TABLE CONVERSATION (
 CONVERSATION_ID NUMBER PRIMARY KEY
 ,SUBJECT NVARCHAR2(200)
 ,STATUS NUMBER 
 ,DATE_CREATED DATE
);
CREATE SEQUENCE SEQ_CONV_ID;

CREATE TABLE USER_CONV (
  CONVERSATION_ID NUMBER
 ,USER_ID NUMBER
 ,STATUS NUMBER
 ,DATE_CREATED DATE
);

CREATE TABLE MESSAGE (
  MESSAGE_ID NUMBER PRIMARY KEY
 ,MESS_BODY NVARCHAR2(500)
 ,STATUS NUMBER
 ,MESS_TYPE NUMBER
 ,FROM_USER_ID NUMBER
 ,CONVERSATION_ID NUMBER
 ,DATE_SENT DATE
 ,DATE_DELIVERED DATE
 ,CLIENT_MESSAGE_ID NUMBER
);
COMMENT ON COLUMN MESSAGE.STATUS IS '1: SENT; 2:DELIVERIED';
CREATE SEQUENCE SEQ_MESS_ID;

CREATE TABLE BUDDY (
  USER_ID NUMBER
 ,BUDDY_ID NUMBER
 ,STATUS NUMBER
 ,DATE_CREATED DATE
);

--DROP TABLE MESSAGE_USER;
CREATE TABLE MESSAGE_USER (
  MESSAGE_ID NUMBER
 ,USER_ID NUMBER
 ,STATUS NUMBER
 ,DATE_SENT DATE
 ,DATE_RECEIVED DATE
);